[package]
name = "sonido"
version = "0.1.0"
authors = ["autom"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.11.0"
hound = "3.4.0"